# ===== ZMK Studio (live keymap editing over USB, on central) =====
CONFIG_ZMK_STUDIO=y

# ===== Pointing / PMW3610 trackball =====
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y

# ===== Free NFC pins P0.09 (col3) & P0.10 (RGB) for GPIO =====
CONFIG_NFCT_PINS_AS_GPIOS=y
